version: "3.8"
services:
  postgre_db:
    container_name: postgre_db
    hostname: postgre_db
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgre:/data/db

volumes:
  postgre:
